"""Implementation of statechart lock_controller.
Generated by itemis CREATE code generator.
"""

import queue
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../lib')))
from yakindu.rx import Observable

class LockController:
	"""Implementation of the state machine LockController.
	"""

	class State:
		""" State Enum
		"""
		(
			main_region_a,
			main_region_b,
			main_region_c,
			main_region_d,
			main_region_e,
			null_state
		) = range(6)
	
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		
		self.LOW = 0
		self.HIGH = 1
		self.LOW_LVL = 500
		self.HIGH_LVL = 1500
		self.request_lvl_change = None
		self.water_lvl = None
		self.water_lvl_value = None
		self.resume = None
		self.door_obstructed = None
		self.set_request_pending = None
		self.set_request_pending_value = None
		self.set_request_pending_observable = Observable()
		self.set_sensor_broken = None
		self.set_sensor_broken_observable = Observable()
		self.open_flow = None
		self.open_flow_value = None
		self.open_flow_observable = Observable()
		self.close_flow = None
		self.close_flow_value = None
		self.close_flow_observable = Observable()
		self.open_doors = None
		self.open_doors_value = None
		self.open_doors_observable = Observable()
		self.close_doors = None
		self.close_doors_value = None
		self.close_doors_observable = Observable()
		self.green_light = None
		self.green_light_value = None
		self.green_light_observable = Observable()
		self.red_light = None
		self.red_light_value = None
		self.red_light_observable = Observable()
		
		self.in_event_queue = queue.Queue()
		
		# enumeration of all states:
		self.__State = LockController.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 1
		for __state_index in range(1):
			self.__state_vector[__state_index] = self.State.null_state
		
		# for timed statechart:
		self.timer_service = None
		self.__time_events = [None] * 2
		
		# initializations:
		self.__is_executing = False
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.main_region_a:
			return self.__state_vector[0] == self.__State.main_region_a
		if s == self.__State.main_region_b:
			return self.__state_vector[0] == self.__State.main_region_b
		if s == self.__State.main_region_c:
			return self.__state_vector[0] == self.__State.main_region_c
		if s == self.__State.main_region_d:
			return self.__state_vector[0] == self.__State.main_region_d
		if s == self.__State.main_region_e:
			return self.__state_vector[0] == self.__State.main_region_e
		return False
		
	def time_elapsed(self, event_id):
		"""Add time events to in event queue
		"""
		if event_id in range(2):
			self.in_event_queue.put(lambda: self.raise_time_event(event_id))
			self.run_cycle()
	
	def raise_time_event(self, event_id):
		"""Raise timed events using the event_id.
		"""
		self.__time_events[event_id] = True
	
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	
	def raise_request_lvl_change(self):
		"""Raise method for event request_lvl_change.
		"""
		self.in_event_queue.put(self.__raise_request_lvl_change_call)
		self.run_cycle()
	
	def __raise_request_lvl_change_call(self):
		"""Raise callback for event request_lvl_change.
		"""
		self.request_lvl_change = True
	
	def raise_water_lvl(self, value):
		"""Raise method for event water_lvl.
		"""
		self.in_event_queue.put(lambda: self.__raise_water_lvl_call(value))
		self.run_cycle()
	
	def __raise_water_lvl_call(self, value):
		"""Raise callback for event water_lvl.
		"""
		self.water_lvl = True
		self.water_lvl_value = value
	
	def raise_resume(self):
		"""Raise method for event resume.
		"""
		self.in_event_queue.put(self.__raise_resume_call)
		self.run_cycle()
	
	def __raise_resume_call(self):
		"""Raise callback for event resume.
		"""
		self.resume = True
	
	def raise_door_obstructed(self):
		"""Raise method for event door_obstructed.
		"""
		self.in_event_queue.put(self.__raise_door_obstructed_call)
		self.run_cycle()
	
	def __raise_door_obstructed_call(self):
		"""Raise callback for event door_obstructed.
		"""
		self.door_obstructed = True
	
	def __entry_action_main_region_a(self):
		"""Entry action for state 'A'..
		"""
		#Entry action for state 'A'.
		self.open_doors_observable.next(self.LOW)
		self.green_light_observable.next(self.LOW)
		
	def __entry_action_main_region_b(self):
		"""Entry action for state 'B'..
		"""
		#Entry action for state 'B'.
		self.timer_service.set_timer(self, 0, (2 * 1000), False)
		
	def __entry_action_main_region_c(self):
		"""Entry action for state 'C'..
		"""
		#Entry action for state 'C'.
		self.close_doors_observable.next(self.LOW)
		self.open_flow_observable.next(self.HIGH)
		
	def __entry_action_main_region_d(self):
		"""Entry action for state 'D'..
		"""
		#Entry action for state 'D'.
		self.timer_service.set_timer(self, 1, (1 * 1000), False)
		
	def __entry_action_main_region_e(self):
		"""Entry action for state 'E'..
		"""
		#Entry action for state 'E'.
		self.close_flow_observable.next(self.HIGH)
		self.open_doors_observable.next(self.HIGH)
		self.green_light_observable.next(self.HIGH)
		
	def __exit_action_main_region_a(self):
		"""Exit action for state 'A'..
		"""
		#Exit action for state 'A'.
		self.red_light_observable.next(self.LOW)
		
	def __exit_action_main_region_b(self):
		"""Exit action for state 'B'..
		"""
		#Exit action for state 'B'.
		self.timer_service.unset_timer(self, 0)
		
	def __exit_action_main_region_d(self):
		"""Exit action for state 'D'..
		"""
		#Exit action for state 'D'.
		self.timer_service.unset_timer(self, 1)
		
	def __enter_sequence_main_region_a_default(self):
		"""'default' enter sequence for state A.
		"""
		#'default' enter sequence for state A
		self.__entry_action_main_region_a()
		self.__state_vector[0] = self.State.main_region_a
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_b_default(self):
		"""'default' enter sequence for state B.
		"""
		#'default' enter sequence for state B
		self.__entry_action_main_region_b()
		self.__state_vector[0] = self.State.main_region_b
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_c_default(self):
		"""'default' enter sequence for state C.
		"""
		#'default' enter sequence for state C
		self.__entry_action_main_region_c()
		self.__state_vector[0] = self.State.main_region_c
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_d_default(self):
		"""'default' enter sequence for state D.
		"""
		#'default' enter sequence for state D
		self.__entry_action_main_region_d()
		self.__state_vector[0] = self.State.main_region_d
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_e_default(self):
		"""'default' enter sequence for state E.
		"""
		#'default' enter sequence for state E
		self.__entry_action_main_region_e()
		self.__state_vector[0] = self.State.main_region_e
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_default(self):
		"""'default' enter sequence for region main region.
		"""
		#'default' enter sequence for region main region
		self.__react_main_region__entry_default()
		
	def __exit_sequence_main_region_a(self):
		"""Default exit sequence for state A.
		"""
		#Default exit sequence for state A
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region_a()
		
	def __exit_sequence_main_region_b(self):
		"""Default exit sequence for state B.
		"""
		#Default exit sequence for state B
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region_b()
		
	def __exit_sequence_main_region_c(self):
		"""Default exit sequence for state C.
		"""
		#Default exit sequence for state C
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region_d(self):
		"""Default exit sequence for state D.
		"""
		#Default exit sequence for state D
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region_d()
		
	def __exit_sequence_main_region_e(self):
		"""Default exit sequence for state E.
		"""
		#Default exit sequence for state E
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region(self):
		"""Default exit sequence for region main region.
		"""
		#Default exit sequence for region main region
		state = self.__state_vector[0]
		if state == self.State.main_region_a:
			self.__exit_sequence_main_region_a()
		elif state == self.State.main_region_b:
			self.__exit_sequence_main_region_b()
		elif state == self.State.main_region_c:
			self.__exit_sequence_main_region_c()
		elif state == self.State.main_region_d:
			self.__exit_sequence_main_region_d()
		elif state == self.State.main_region_e:
			self.__exit_sequence_main_region_e()
		
	def __react_main_region__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_a_default()
		
	def __react(self, transitioned_before):
		"""Implementation of __react function.
		"""
		#State machine reactions.
		return transitioned_before
	
	
	def __main_region_a_react(self, transitioned_before):
		"""Implementation of __main_region_a_react function.
		"""
		#The reactions of state A.
		transitioned_after = self.__react(transitioned_before)
		if transitioned_after < 0:
			if self.request_lvl_change:
				self.__exit_sequence_main_region_a()
				self.__enter_sequence_main_region_b_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __main_region_b_react(self, transitioned_before):
		"""Implementation of __main_region_b_react function.
		"""
		#The reactions of state B.
		transitioned_after = self.__react(transitioned_before)
		if transitioned_after < 0:
			if self.__time_events[0]:
				self.__exit_sequence_main_region_b()
				self.__time_events[0] = False
				self.__enter_sequence_main_region_c_default()
				transitioned_after = 0
			elif self.door_obstructed:
				self.__exit_sequence_main_region_b()
				self.__enter_sequence_main_region_b_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __main_region_c_react(self, transitioned_before):
		"""Implementation of __main_region_c_react function.
		"""
		#The reactions of state C.
		transitioned_after = self.__react(transitioned_before)
		if transitioned_after < 0:
			if (self.water_lvl) and (self.water_lvl_value >= (self.HIGH_LVL - 30)):
				self.__exit_sequence_main_region_c()
				self.__enter_sequence_main_region_d_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __main_region_d_react(self, transitioned_before):
		"""Implementation of __main_region_d_react function.
		"""
		#The reactions of state D.
		transitioned_after = self.__react(transitioned_before)
		if transitioned_after < 0:
			if self.__time_events[1]:
				self.__exit_sequence_main_region_d()
				self.__time_events[1] = False
				self.__enter_sequence_main_region_e_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __main_region_e_react(self, transitioned_before):
		"""Implementation of __main_region_e_react function.
		"""
		#The reactions of state E.
		return self.__react(transitioned_before)
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.request_lvl_change = False
		self.water_lvl = False
		self.resume = False
		self.door_obstructed = False
		self.__time_events[0] = False
		self.__time_events[1] = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		state = self.__state_vector[0]
		if state == self.State.main_region_a:
			self.__main_region_a_react(-1)
		elif state == self.State.main_region_b:
			self.__main_region_b_react(-1)
		elif state == self.State.main_region_c:
			self.__main_region_c_react(-1)
		elif state == self.State.main_region_d:
			self.__main_region_d_react(-1)
		elif state == self.State.main_region_e:
			self.__main_region_e_react(-1)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__micro_step()
			self.__clear_in_events()
			condition_0 = False
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
				condition_0 = True
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart LockController
		self.__enter_sequence_main_region_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart LockController
		self.__exit_sequence_main_region()
		self.__state_vector[0] = self.State.null_state
		self.__is_executing = False
	
	
	def trigger_without_event(self):
		"""Implementation of triggerWithoutEvent function.
		"""
		self.run_cycle()
	
