/* Simulation code for Assignment1.Gantry_system_block generated by the OpenModelica Compiler OpenModelica 1.24.0. */
#if !defined(Gantry_system_block__MODEL_H)
#define Gantry_system_block__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "Gantry_system_block_functions.h"


extern void Gantry_system_block_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void Gantry_system_block_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int Gantry_system_block_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_checkForAsserts(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int Gantry_system_block_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* Gantry_system_block_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* Gantry_system_block_relationDescription(int i);
extern void Gantry_system_block_function_initSample(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Gantry_system_block_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Gantry_system_block_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Gantry_system_block_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Gantry_system_block_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Gantry_system_block_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Gantry_system_block_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int Gantry_system_block_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Gantry_system_block_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Gantry_system_block_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Gantry_system_block_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Gantry_system_block_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Gantry_system_block_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int Gantry_system_block_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* Gantry_system_block_linear_model_frame(void);
extern const char* Gantry_system_block_linear_model_datarecovery_frame(void);
extern int Gantry_system_block_mayer(DATA* data, modelica_real** res, short *);
extern int Gantry_system_block_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int Gantry_system_block_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int Gantry_system_block_setInputData(DATA *data, const modelica_boolean file);
extern int Gantry_system_block_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void Gantry_system_block_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void Gantry_system_block_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int Gantry_system_block_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void Gantry_system_block_read_simulation_info(SIMULATION_INFO* simulationData);
extern void Gantry_system_block_read_input_fmu(MODEL_DATA* modelData);
extern void Gantry_system_block_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int Gantry_system_block_inputNames(DATA* data, char ** names);
extern int Gantry_system_block_dataReconciliationInputNames(DATA* data, char ** names);
extern int Gantry_system_block_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int Gantry_system_block_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int Gantry_system_block_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int Gantry_system_block_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "Gantry_system_block_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(Gantry_system_block__MODEL_H) */


