/* Additional record code for Gantry_system_block generated by the OpenModelica Compiler OpenModelica 1.24.0. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Gantry_system_block_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

